### ISSUE TITLE
replicated to hosting provider - which file to put the agoraAppId in?

### ISSUE THREAD

**Issue by soneups** [digitallysavvy/group-video-chat#7]
Hi,

I suspect I'm missing a simple step but i have copied these files to a hosted website and i keep getting prompted to put in the app id and channel name - which file should i put my app id setting in? - Also even in putting them in manually the video stream do not appear to start - the same is true if i try your demo site - any clues greatly appreciated.

**Comment by FatGrizzly** [comment]
Hello hermes can we remove that popup that pops when i open the link.Instead can i put the APPID in .js itself

**Comment by akshatvg** [comment]
@soundarrr yes you can disable the modal by removing its code and put the App ID hardcoded in the JS file or use a .env for the same.

**Comment by akshatvg** [comment]
@soneups you have to create an App Id at the [Agora Web Console](https://console.agora.io/). Channel name can be anything you want.

**Comment by FatGrizzly** [comment]
@akshatvg Thanks for the clarification 😃
