### ISSUE TITLE
Failed to load remote server

### ISSUE THREAD

**Issue by aravind1999** [digitallysavvy/group-video-chat#9]
Live reload enabled.
AgoraRTCSDK-3.1.1.js:2 13:35:37:963 Agora-SDK [INFO]: Creating client, MODE: rtc CODEC: h264
AgoraRTCSDK-3.1.1.js:2 13:35:37:969 Agora-SDK [INFO]: Creating client, MODE: rtc CODEC: vp8
AgoraRTCSDK-3.1.1.js:2 13:35:37:970 Agora-SDK [INFO]: [D09D5] Initializing AgoraRTC client, appId: df93bd35257f481591a42da6641b578b.
agora-interface.js:34 AgoraRTC client initialized
AgoraRTCSDK-3.1.1.js:2 13:35:37:971 Agora-SDK [INFO]: processId: process-dd0000b3-bcf0-420c-aae1-fe460a5a243f
AgoraRTCSDK-3.1.1.js:2 13:35:37:972 Agora-SDK [DEBUG]: Flush cached event reporting: 3
AgoraRTCSDK-3.1.1.js:2 13:35:37:975 Agora-SDK [DEBUG]: [D09D5] Connect to choose_server: https://webrtc2-ap-web-1.agora.io/api/v1
AgoraRTCSDK-3.1.1.js:2 13:35:37:976 Agora-SDK [DEBUG]: [D09D5] Connect to choose_server: https://webrtc2-ap-web-2.agoraio.cn/api/v1
AgoraRTCSDK-3.1.1.js:2 13:35:37:977 Agora-SDK [INFO]: [D09D5] Adding event handler on stream-published
AgoraRTCSDK-3.1.1.js:2 13:35:37:985 Agora-SDK [INFO]: [D09D5] Added event handler on stream-published, stream-added, stream-subscribed, peer-leave, mute-audio, unmute-audio, mute-video, unmute-video
AgoraRTCSDK-3.1.1.js:2 13:35:38:220 Agora-SDK [DEBUG]: [D09D5] Get gateway address: Array(3)
AgoraRTCSDK-3.1.1.js:2 13:35:38:221 Agora-SDK [INFO]: [D09D5] Joining channel: 720p
AgoraRTCSDK-3.1.1.js:2 13:35:38:224 Agora-SDK [DEBUG]: [D09D5] register client Channel 720p Uid 942358029
AgoraRTCSDK-3.1.1.js:2 13:35:38:230 Agora-SDK [DEBUG]: [D09D5] start connect:123-108-46-74.edge.agora.io:5889
AgoraRTCSDK-3.1.1.js:2 13:35:38:403 Agora-SDK [DEBUG]: [D09D5] websockect opened: 123-108-46-74.edge.agora.io:5889
AgoraRTCSDK-3.1.1.js:2 13:35:38:404 Agora-SDK [DEBUG]: [D09D5] Connected to gateway server
AgoraRTCSDK-3.1.1.js:2 13:35:38:405 Agora-SDK [DEBUG]: TurnServers config Array(1)
AgoraRTCSDK-3.1.1.js:2 13:35:38:476 Agora-SDK [INFO]: [D09D5] Join channel 720p success, join with uid: 942358029.
agora-interface.js:127 User 942358029 join channel successfully
AgoraRTCSDK-3.1.1.js:2 13:35:38:480 Agora-SDK [DEBUG]: Create stream
AgoraRTCSDK-3.1.1.js:2 13:35:38:489 Agora-SDK [DEBUG]: [942358029] Requested access to local media
AgoraRTCSDK-3.1.1.js:2 13:35:38:491 Agora-SDK [DEBUG]: GetUserMedia {"video":{"width":640,"height":480,"frameRate":{"ideal":30,"max":30}},"audio":{}}
AgoraRTCSDK-3.1.1.js:2 13:35:38:681 Agora-SDK [DEBUG]: [942358029] User has granted access to local media
AgoraRTCSDK-3.1.1.js:2 13:35:38:683 Agora-SDK [DEBUG]: start vsResHack MediaStream
agora-interface.js:148 getUserMedia successfully
AgoraRTCSDK-3.1.1.js:2 13:35:38:688 Agora-SDK [DEBUG]: [942358029] play(). local-video undefined
AgoraRTCSDK-3.1.1.js:2 13:35:38:699 Agora-SDK [INFO]: [D09D5] Publishing stream, uid 942358029
AgoraRTCSDK-3.1.1.js:2 13:35:38:822 Agora-SDK [DEBUG]: [D09D5]Created webkitRTCPeerConnnection with config "{"iceServers":[{"url":"stun:webcs.agora.io:3478"},{"username":"test","credential":"111111","credentialType":"password","urls":"turn:123-108-46-74.edge.agora.io:5919?transport=udp"},{"username":"test","credential":"111111","credentialType":"password","urls":"turn:123-108-46-74.edge.agora.io:5919?transport=tcp"}],"sdpSemantics":"plan-b"}".
AgoraRTCSDK-3.1.1.js:2 13:35:38:823 Agora-SDK [DEBUG]: [D09D5] PeerConnection add stream : MediaStream
AgoraRTCSDK-3.1.1.js:2 13:35:38:864 Agora-SDK [DEBUG]: [vsResHack] get stream resolution:  640 x 480 MediaStream
AgoraRTCSDK-3.1.1.js:2 13:35:38:867 Agora-SDK [DEBUG]: [942358029] video dimensions: 640 480
favicon.ico:1 Failed to load resource: the server responded with a status of 404 (Not Found)
AgoraRTCSDK-3.1.1.js:2 13:35:38:936 Agora-SDK [DEBUG]: [D09D5]srflx candidate : null relay candidate: null host candidate : a=candidate:1221703924 1 udp 2122260223 192.168.0.105 50605 typ host generation 0 network-id 1 network-cost 10

AgoraRTCSDK-3.1.1.js:2 13:35:38:938 Agora-SDK [DEBUG]: [D09D5] SDP exchange in publish : send offer --   Object
AgoraRTCSDK-3.1.1.js:2 13:35:38:981 Agora-SDK [INFO]: [D09D5] Local stream published with uid 942358029
AgoraRTCSDK-3.1.1.js:2 13:35:38:981 Agora-SDK [DEBUG]: [D09D5] SDP exchange in publish : receive answer --   Object
AgoraRTCSDK-3.1.1.js:2 13:35:38:982 Agora-SDK [DEBUG]: [D09D5]Set Video Bitrate - min:100 max:750
AgoraRTCSDK-3.1.1.js:2 13:35:39:20 Agora-SDK [DEBUG]: [D09D5] publish p2p connected:  Map(1)
AgoraRTCSDK-3.1.1.js:2 13:35:39:21 Agora-SDK [DEBUG]: Flush cached event reporting: 5
AgoraRTCSDK-3.1.1.js:2 13:35:39:21 Agora-SDK [INFO]: [D09D5] Publish success, uid: 942358029
agora-interface.js:43 Publish local stream successfully
AgoraRTCSDK-3.1.1.js:2 13:35:39:436 Agora-SDK [DEBUG]: [D09D5]: Period fir change to: false
AgoraRTCSDK-3.1.1.js:2 13:35:40:864 Agora-SDK [DEBUG]: [942358029] Media Player Status Change Object
AgoraRTCSDK-3.1.1.js:2 13:35:40:868 Agora-SDK [DEBUG]: [942358029] Media Player Status Change Object
AgoraRTCSDK-3.1.1.js:2 13:35:43:685 Agora-SDK [WARNING]: [942358029] Stream.disableVideo is deprecated and will be removed in the future. Use Stream.muteVideo instead
e @ AgoraRTCSDK-3.1.1.js:2
AgoraRTCSDK-3.1.1.js:2 13:35:43:685 Agora-SDK [DEBUG]: [942358029] Muted video stream with id 942358029
AgoraRTCSDK-3.1.1.js:2 13:35:46:189 Agora-SDK [WARNING]: [942358029] Stream.enableVideo is deprecated and will be removed in the future. Use Stream.unmuteVideo instead
e @ AgoraRTCSDK-3.1.1.js:2
AgoraRTCSDK-3.1.1.js:2 13:35:46:190 Agora-SDK [DEBUG]: [942358029] Unmuted video stream with id 942358029
ui.js:27 so sad to see you leave the channel
AgoraRTCSDK-3.1.1.js:2 13:35:47:877 Agora-SDK [INFO]: [D09D5] Leaving channel
AgoraRTCSDK-3.1.1.js:2 13:35:47:878 Agora-SDK [DEBUG]: [D09D5] unregister client  942358029
AgoraRTCSDK-3.1.1.js:2 13:35:47:880 Agora-SDK [INFO]: [D09D5] Leave channel before joined
AgoraRTCSDK-3.1.1.js:2 13:35:47:889 Agora-SDK [DEBUG]: renewSession C5468222C2D642F3A41FECF4D993AB20 => E0B1BE2EE918471FA5B4412BD876A1BA
agora-interface.js:168 client leaves channel
AgoraRTCSDK-3.1.1.js:2 13:35:48:29 Agora-SDK [DEBUG]: [D09D5] No socket available
AgoraRTCSDK-3.1.1.js:2 13:35:48:30 Agora-SDK [DEBUG]: [D09D5] Socket emit report failed {"_type":"publish_stats","_message":{"stream_type":"high","stats":{"id":"ssrc_368239328_send","timestamp":"2020-07-07T08:05:47.824Z","type":"ssrc","A_ail":"3869","packetsLost":"0","A_rtt":"29","A_relrm":"0","A_ecrle":"0","totalSamplesDuration":"8.97","A_cn":"opus","mediaType":"audio","A_ecrl":"-30","A_rel":"0","totalAudioEnergy":"0.0716043","ssrc":"368239328","A_jr":"19","googTypingNoiseState":"false","packetsSent":"437","bytesSent":"43197","A_astd":"0"}}}
AgoraRTCSDK-3.1.1.js:2 13:35:48:229 Agora-SDK [DEBUG]: [D09D5] No socket available
AgoraRTCSDK-3.1.1.js:2 13:35:48:230 Agora-SDK [DEBUG]: [D09D5] Socket emit report failed {"_type":"publish_stats","_message":{"stream_type":"high","stats":{"id":"bweforvideo","timestamp":"2020-07-07T08:05:47.824Z","type":"VideoBwe","A_aeb":"675640","A_asb":"750000","A_rb":"0","A_arb":"0","A_teb":"748800","A_bd":"0","A_tb":"695592"}}}
AgoraRTCSDK-3.1.1.js:2 13:35:48:437 Agora-SDK [DEBUG]: [D09D5] No socket available
ui.js:27 so sad to see you leave the channel
AgoraRTCSDK-3.1.1.js:2 13:35:48:715 Agora-SDK [INFO]: [D09D5] Leaving channel
AgoraRTCSDK-3.1.1.js:2 13:35:48:716 Agora-SDK [ERROR]: [D09D5]  GATEWEAY_CLIENT_UNREGISTERED
AgoraRTCSDK-3.1.1.js:2 13:35:48:716 Agora-SDK [DEBUG]: [D09D5] Client Already in DISCONNECTED status
AgoraRTCSDK-3.1.1.js:2 13:35:48:716 Agora-SDK [DEBUG]: renewSession E0B1BE2EE918471FA5B4412BD876A1BA => 481B10F700224FCCA6F9E3A0A868B8F4
agora-interface.js:168 client leaves channel
AgoraRTCSDK-3.1.1.js:2 13:35:49:894 Agora-SDK [WARNING]: [942358029] Stream.enableAudio is deprecated and will be removed in the future. Use Stream.unmuteAudio instead
e @ AgoraRTCSDK-3.1.1.js:2
AgoraRTCSDK-3.1.1.js:2 13:35:49:894 Agora-SDK [WARNING]: [942358029] User already enableAudio
e @ AgoraRTCSDK-3.1.1.js:2
AgoraRTCSDK-3.1.1.js:2 13:35:49:895 Agora-SDK [DEBUG]: [942358029] Unmuted audio stream with id  942358029
AgoraRTCSDK-3.1.1.js:2 13:35:50:265 Agora-SDK [WARNING]: [942358029] Stream.disableAudio is deprecated and will be removed in the future. Use Stream.muteAudio instead
e @ AgoraRTCSDK-3.1.1.js:2
AgoraRTCSDK-3.1.1.js:2 13:35:50:265 Agora-SDK [DEBUG]: [942358029] Muted audio stream with id  942358029
AgoraRTCSDK-3.1.1.js:2 13:35:50:266 Agora-SDK [DEBUG]: [D09D5] No socket available
AgoraRTCSDK-3.1.1.js:2 13:35:50:266 Agora-SDK [DEBUG]: [D09D5] Socket emit report failed {"_type":"control","_message":{"action":"mute_local_audio","stream_id":942358029}}
AgoraRTCSDK-3.1.1.js:2 13:35:51:226 Agora-SDK [DEBUG]: [942358029] Unmuted audio stream with id  942358029
AgoraRTCSDK-3.1.1.js:2 13:35:51:226 Agora-SDK [DEBUG]: [D09D5] No socket available
AgoraRTCSDK-3.1.1.js:2 13:35:51:226 Agora-SDK [DEBUG]: [D09D5] Socket emit report failed {"_type":"control","_message":{"action":"unmute_local_audio","stream_id":942358029}}
AgoraRTCSDK-3.1.1.js:2 13:35:52:919 Agora-SDK [DEBUG]: [942358029] Muted audio stream with id  942358029
AgoraRTCSDK-3.1.1.js:2 13:35:52:919 Agora-SDK [DEBUG]: [D09D5] No socket available
AgoraRTCSDK-3.1.1.js:2 13:35:52:920 Agora-SDK [DEBUG]: [D09D5] Socket emit report failed {"_type":"control","_message":{"action":"mute_local_audio","stream_id":942358029}}

**Comment by digitallysavvy** [comment]
The CORS issue is not a breaking error... this isn't an issue with this project, its an issue that should be raised with Agora's support team.
